---
title: "Model summary"
output: html_document
---
   
## Variable descriptions

For observation $i$, term

1. $\text{Sqm}_i$ is the size of the apartment measured in square meters,
2. $\text{GoodConditionSqm}_i$ is an interaction term of the size of the apartment and the condition of the apartment,
    + $\text{GoodConditionSqm}_i$ gets the same value as $\text{Sqm}_i$ if the condition of the apartment is listed as good and 0 otherwise. 
3. $\text{Age}_i$ is the age of the building where the apartment is located measured as the difference between the year the building was built and 2019,
4. $\text{TwoRoomsDummy}_i$ is a dummy variable describing whether the apartment was listed to have 2 rooms,
5. $\text{ThreeRoomsDummy}_i$ is a dummy variable describing whether the apartment was listed to have 3 rooms,
6. $\text{FourRoomsOrModeDummy}_i$ is a dummy variable describing whether the apartment was listed to have 4 rooms or more,
7. $\text{OwnFloor}_i$ is the floor where the apartment was located

and 

8. $\text{SaunaDummy}_i$ is a dummy variable describing whether the apartment was listed to have a sauna.
 
Model 3 utilizes the ocean and road distances for the group level mean. For neighborhood $j$, term 

1. $\text{OceanDistance}_j$ is the distance of the neighborhood centroid to the ocean polygon 'as the crow flies', i.e. a direct distance,

and

2. $\text{RoadDistance}_j$ is the distance of the neighborhood centroid to a point representing the center of Helsinki along the road network.

Both terms $\text{OceanDistance}_j$ and $\text{RoadDistance}_j$ are measured in meters. 

Model 4 utilizes inter-centroid distances. The direct distance between the centroids of neighborhoods $i$ and $j$ is denoted by the term $D_{ij}$. These distancers are measured in kilometers.  

Finally, $\text{Price}_i$ is the sales price for observation $i$. 

## Chosen approach for choosing priors

The priors for the parameters were not chosen on any domain-specific expertise about the expected size of effects etc. The approach was rather first deciding the expected direction of the effect on price for each of the variables. Then the values for the expected values and for the dispersions parameters were chosen by simulating data from the joint distribution with these values: If the histograms of the generated sales prices were 'roughly' reasonable over many simulations, the values were seen as acceptable (Data generated with this approach and this joint distribution aslo generated negative sales parameters which could be seen as a weakness). 

The prior for the $\nu$-parameter was chosen on the basis of suggestions from mcstan.org for Student's t distributions. 

## Model 1

### Priors

$\beta_{\text{Intercept}} \sim \text{N}(70000, 50000^2) \\
\beta_{\text{Sqm}} \sim \text{N}(4500, 1000^2) \\
\beta_{\text{Sqm, Good Condition}} \sim \text{N}(1000, 1000^2) \\
\beta_{\text{Age}} \sim \text{N}(-1500, 2000^2) \\
\beta_{\text{TwoRoomsDummy}} \sim \text{N}(5000, 10000^2) \\
\beta_{\text{ThreeRoomsDummy}} \sim \text{N}(7500, 10000^2) \\
\beta_{\text{FourRoomsOrMoreDummy}} \sim \text{N}(7500, 10000^2) \\
\beta_{\text{OwnFloor}} \sim \text{N}(7000, 1000^2) \\
\beta_{\text{SaunaDummy}} \sim \text{N}(5000, 2500^2) \\
\sigma \sim \text{HalfCauchy}(15000) \\
\nu \sim \text{Gamma}(2, 0.1)$

### Expected value $\mu_i$ for observation $i$

$\mu_i = \beta_{\text{Intercept}} + \beta_{\text{Sqm}} \text{Sqm}_i + \beta_{\text{Sqm, Good Condition}} \text{GoodConditionSqm}_i + \beta_{\text{Age}} \text{Age}_i + \beta_{\text{TwoRoomsDummy}} \text{TwoRoomsDummy}_i + \\
\qquad{ }         \beta_{\text{ThreeRoomsDummy}} \text{ThreeRoomsDummy}_i + \beta_{\text{FourRoomsOrMoreDummy}} \text{FourRoomsOrModeDummy}_i + \beta_{\text{OwnFloor}} \text{OwnFloor}_i + \\
\qquad{ }          \beta_{\text{SaunaDummy}} \text{SaunaDummy}_i$

### Likelihood (generalized Student's t)

$\text{Price}_i \sim t_\nu(\mu_i, \sigma)$ 

## Model 2 

Implementation done with non-centered parameterization!

### Group varying coefficients over neighborhoods 

$\mu_{\text{Intercept}} \sim \text{N}(50000, 50000^2) \\
\sigma_{\text{Intercept}} \sim \text{HalfCauchy}(11000) \\
\beta_{\text{Intercept}, j } \sim \text{N}(\mu_{\text{Intercept}}, \sigma^2_{\text{Intercept}}), j = 1, \ldots, 130$

### Priors

$\beta_{\text{Sqm}} \sim \text{N}(4000, 1000^2) \\
\beta_{\text{Sqm, Good Condition}} \sim \text{N}(1000, 1000^2) \\
\beta_{\text{Age}} \sim \text{N}(-1500, 2000^2) \\
\beta_{\text{TwoRoomsDummy}} \sim \text{N}(5000, 10000^2) \\
\beta_{\text{ThreeRoomsDummy}} \sim \text{N}(7500, 10000^2) \\
\beta_{\text{FourRoomsOrMoreDummy}} \sim \text{N}(7500, 10000^2) \\
\beta_{\text{OwnFloor}} \sim \text{N}(7000, 1000^2) \\
\beta_{\text{SaunaDummy}} \sim \text{N}(5000, 2500^2) \\
\sigma \sim \text{HalfCauchy}(15000) \\
\nu \sim \text{Gamma}(2, 0.1)$

### Expected value $\mu_i$ for observation $i$

$\mu_i = \beta_{\text{Intercept}, j[i]} + \beta_{\text{Sqm}} \text{Sqm}_i + \beta_{\text{Sqm, Good Condition}} \text{GoodConditionSqm}_i + \beta_{\text{Age}} \text{Age}_i + \beta_{\text{TwoRoomsDummy}} \text{TwoRoomsDummy}_i + \\
\qquad{ }         \beta_{\text{ThreeRoomsDummy}} \text{ThreeRoomsDummy}_i + \beta_{\text{FourRoomsOrMoreDummy}} \text{FourRoomsOrModeDummy}_i + \beta_{\text{OwnFloor}} \text{OwnFloor}_i + \\
\qquad{ }          \beta_{\text{SaunaDummy}} \text{SaunaDummy}_i$

### Likelihood (generalized Student's t)

$\text{Price}_i \sim t_\nu(\mu_i, \sigma)$ 

## Model 3

Implementation done with non-centered parameterization!

### Group varying coefficients over neighborhoods 

$\alpha_{\text{Intercept}} \sim \text{N}(150000, 50000^2) \\
\alpha_{\text{OceanDistance}} \sim \text{N}(-5, 3^2) \\
\alpha_{\text{RoadDistance}} \sim \text{N}(-5, 3^2) \\
\sigma_{\text{Intercept}} \sim \text{HalfCauchy}(20000) \\
\beta_{\text{Intercept}, j } \sim \text{N}(\alpha_{\text{Intercept}} + \alpha_{\text{OceanDistance}} \text{OceanDistance}_j + \alpha_{\text{RoadDistance}} \text{RoadDistance}_j, \sigma^2_{\text{Intercept}}), j = 1, \ldots, 130$

### Priors

$\beta_{\text{Sqm}} \sim \text{N}(5000, 1000^2) \\
\beta_{\text{Sqm, Good Condition}} \sim \text{N}(2000, 1000^2) \\
\beta_{\text{Age}} \sim \text{N}(-1000, 1000^2) \\
\beta_{\text{TwoRoomsDummy}} \sim \text{N}(5000, 10000^2) \\
\beta_{\text{ThreeRoomsDummy}} \sim \text{N}(7500, 10000^2) \\
\beta_{\text{FourRoomsOrMoreDummy}} \sim \text{N}(7500, 10000^2) \\
\beta_{\text{OwnFloor}} \sim \text{N}(1000, 1000^2) \\
\beta_{\text{SaunaDummy}} \sim \text{N}(5000, 2500^2) \\
\sigma \sim \text{HalfCauchy}(15000) \\
\nu \sim \text{Gamma}(2, 0.1)$

### Expected value $\mu_i$ for observation $i$

$\mu_i = \beta_{\text{Intercept}, j[i]} + \beta_{\text{Sqm}} \text{Sqm}_i + \beta_{\text{Sqm, Good Condition}} \text{GoodConditionSqm}_i + \beta_{\text{Age}} \text{Age}_i + \beta_{\text{TwoRoomsDummy}} \text{TwoRoomsDummy}_i + \\
\qquad{ }         \beta_{\text{ThreeRoomsDummy}} \text{ThreeRoomsDummy}_i + \beta_{\text{FourRoomsOrMoreDummy}} \text{FourRoomsOrModeDummy}_i + \beta_{\text{OwnFloor}} \text{OwnFloor}_i + \\
\qquad{ }          \beta_{\text{SaunaDummy}} \text{SaunaDummy}_i$

### Likelihood (generalized Student's t)

$\text{Price}_i \sim t_\nu(\mu_i, \sigma)$ 

## Model 4

Implementation done with non-centered parameterization!

### Group varying coefficients over neighborhoods 

$\beta_{\text{Intercept}} \sim \text{MVNormal}([70, \ldots, 70]',$***$\text{K}$***$)$ 

such that 

$K_{ij} = \eta^2 \text{exp}(-\rho^2 D^2_{ij}) + \delta_{ij} \ 0.01$

Priors for variance terms at group-level

$\rho^2 \sim \text{HalfCauchy}(1) \\
\eta^2 \sim \text{HalfCauchy}(300)$

### Priors

$\beta_{\text{Sqm}} \sim \text{N}(6000, 3000^2) \\
\beta_{\text{Sqm, Good Condition}} \sim \text{N}(1000, 1500^2) \\
\beta_{\text{Age}} \sim \text{N}(-2000, 2500^2) \\
\beta_{\text{TwoRoomsDummy}} \sim \text{N}(5000, 10000^2) \\
\beta_{\text{ThreeRoomsDummy}} \sim \text{N}(7500, 10000^2) \\
\beta_{\text{FourRoomsOrMoreDummy}} \sim \text{N}(7500, 10000^2) \\
\beta_{\text{OwnFloor}} \sim \text{N}(1000, 1000^2) \\
\beta_{\text{SaunaDummy}} \sim \text{N}(5000, 2500^2) \\
\sigma \sim \text{HalfCauchy}(15000) \\
\nu \sim \text{Gamma}(2, 0.1)$

### Expected value $\mu_i$ for observation $i$

$\mu_i = 1000 \cdot \beta_{\text{Intercept}, j[i]} + \beta_{\text{Sqm}} \text{Sqm}_i + \beta_{\text{Sqm, Good Condition}} \text{GoodConditionSqm}_i + \beta_{\text{Age}} \text{Age}_i + \beta_{\text{TwoRoomsDummy}} \text{TwoRoomsDummy}_i + \\
\qquad{ }         \beta_{\text{ThreeRoomsDummy}} \text{ThreeRoomsDummy}_i + \beta_{\text{FourRoomsOrMoreDummy}} \text{FourRoomsOrModeDummy}_i + \beta_{\text{OwnFloor}} \text{OwnFloor}_i + \\
\qquad{ }          \beta_{\text{SaunaDummy}} \text{SaunaDummy}_i$

### Likelihood (generalized Student's t)

$\text{Price}_i \sim t_\nu(\mu_i, \sigma)$ 

## Model 5

Implementation done with non-centered parameterization!

### Group varying coefficients over neighborhoods 

$\alpha \sim \text{MVNormal}( \mu_{\text{coef}}, \text{S})$ 

where

$\mu_{\text{coef}} = [\mu_{\text{coef},1}, \mu_{\text{coef},2}, \mu_{\text{coef},3}]$  s.t. 

1. $\mu_{\text{coef},1} \sim \text{N}(50000, 50000^2)$
2. $\mu_{\text{coef},2} \sim \text{N}(4000, 1000^2)$
3. $\mu_{\text{coef},3} \sim \text{N}(1000, 1000^2)$

and $\text{S} = \text{Diag}(\sigma_{\text{coef}})\  R\  \text{Diag}(\sigma_{\text{coef}}), \  \sigma_{\text{coef}} = [\sigma_{\text{coef},1}, \sigma_{\text{coef},2}, \sigma_{\text{coef},3}]$ s.t.

1. $R \sim \text{LKJcorr}(2)$
2. $\sigma_{\text{coef},1} \sim \text{HalfCauchy}(7000)$
3. $\sigma_{\text{coef},2} \sim \text{HalfCauchy}(1500)$
4. $\sigma_{\text{coef},3} \sim \text{HalfCauchy}(350)$

### Priors

$\beta_{\text{Age}} \sim \text{N}(-2000, 1500^2) \\
\beta_{\text{TwoRoomsDummy}} \sim \text{N}(5000, 5000^2) \\
\beta_{\text{ThreeRoomsDummy}} \sim \text{N}(7500, 5000^2) \\
\beta_{\text{FourRoomsOrMoreDummy}} \sim \text{N}(7500, 5000^2) \\
\beta_{\text{OwnFloor}} \sim \text{N}(1000, 1000^2) \\
\beta_{\text{SaunaDummy}} \sim \text{N}(5000, 2500^2) \\
\sigma \sim \text{HalfCauchy}(15000) \\
\nu \sim \text{Gamma}(2, 0.1)$

### Expected value $\mu_i$ for observation $i$

$\mu_i = \alpha_{1, j[i]} + \alpha_{2, j[i]} \text{Sqm}_i + \alpha_{3, j[i]} \text{GoodConditionSqm}_i + \beta_{\text{Age}} \text{Age}_i + \beta_{\text{TwoRoomsDummy}} \text{TwoRoomsDummy}_i + \\
\qquad{ }         \beta_{\text{ThreeRoomsDummy}} \text{ThreeRoomsDummy}_i + \beta_{\text{FourRoomsOrMoreDummy}} \text{FourRoomsOrModeDummy}_i + \beta_{\text{OwnFloor}} \text{OwnFloor}_i + \\
\qquad{ }          \beta_{\text{SaunaDummy}} \text{SaunaDummy}_i$

### Likelihood (generalized Student's t)

$\text{Price}_i \sim t_\nu(\mu_i, \sigma)$ 